from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]

RUGD_PROCESSED_DIR = PROJECT_ROOT / "data" / "processed" / "RUGD"

RUGD_IMAGES_DIR = RUGD_PROCESSED_DIR / "images"
RUGD_MASKS_ID_DIR = RUGD_PROCESSED_DIR / "masks_id"
RUGD_SPLITS_DIR = RUGD_PROCESSED_DIR / "splits"
RUGD_TRAIN_SPLIT_PATH = RUGD_SPLITS_DIR / "train.txt"
RUGD_VAL_SPLIT_PATH = RUGD_SPLITS_DIR / "val.txt"
RUGD_TEST_SPLIT_PATH = RUGD_SPLITS_DIR / "test.txt"

RUGD_COLORMAP_PATH = (
    PROJECT_ROOT
    / "data"
    / "raw"
    / "RUGD"
    / "sample"
    / "RUGD_sample-data"
    / "RUGD_annotation-colormap.txt"
)

OUTPUTS_DIR = PROJECT_ROOT / "outputs"
EXPERIMENTS_SUMMARY_PATH = OUTPUTS_DIR / "experiments_summary.csv"
CLASS_WEIGHTS_OUTPUT_DIR = OUTPUTS_DIR / "class_weights"
RUGD_CLASS_WEIGHTS_CSV_PATH = CLASS_WEIGHTS_OUTPUT_DIR / "rugd_class_weights.csv"
RUGD_CLASS_WEIGHTS_NPY_PATH = CLASS_WEIGHTS_OUTPUT_DIR / "rugd_class_weights.npy"

UNET_RESNET34_OUTPUT_DIR = OUTPUTS_DIR / "unet_resnet34"
UNET_RESNET34_CHECKPOINT_PATH = UNET_RESNET34_OUTPUT_DIR / "unet_resnet34_last.pth"
UNET_RESNET34_BEST_CHECKPOINT_PATH = UNET_RESNET34_OUTPUT_DIR / "unet_resnet34_best.pth"
UNET_RESNET34_HISTORY_PATH = UNET_RESNET34_OUTPUT_DIR / "history.csv"
UNET_RESNET34_STEP_HISTORY_PATH = UNET_RESNET34_OUTPUT_DIR / "step_history.csv"
UNET_RESNET34_METRICS_PATH = UNET_RESNET34_OUTPUT_DIR / "metrics.txt"
UNET_RESNET34_BEST_METRICS_PATH = UNET_RESNET34_OUTPUT_DIR / "best_metrics.txt"
UNET_RESNET34_TRAINING_CURVES_PATH = UNET_RESNET34_OUTPUT_DIR / "training_curves.png"
UNET_RESNET34_STEP_LOSS_CURVE_PATH = UNET_RESNET34_OUTPUT_DIR / "step_loss_curve.png"
UNET_RESNET34_PREDICTIONS_GRID_PATH = (
    UNET_RESNET34_OUTPUT_DIR / "predictions_grid.png"
)

CLASS_WEIGHTS_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
RUGD_SPLITS_DIR.mkdir(parents=True, exist_ok=True)
UNET_RESNET34_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# RUGD class IDs go from 0 to 24.
RUGD_NUM_CLASSES = 25

# Image sizes are divisible by 32, which is convenient for ResNet encoders.
IMAGE_HEIGHT = 256
IMAGE_WIDTH = 320

BATCH_SIZE = 16

# Standard ImageNet normalization for ResNet-based encoders.
IMAGE_MEAN = [0.485, 0.456, 0.406]
IMAGE_STD = [0.229, 0.224, 0.225]

UNET_RESNET34_NUM_EPOCHS = 30
UNET_RESNET34_LEARNING_RATE = 1e-4
UNET_RESNET34_OPTIMIZER = "adam"
UNET_RESNET34_WEIGHT_DECAY = 0.0
UNET_RESNET34_SCHEDULER = "none"
UNET_RESNET34_LOSS = "ce"
UNET_RESNET34_LOG_EVERY_N_BATCHES = 50
UNET_RESNET34_ENCODER_WEIGHTS = "imagenet"
UNET_RESNET34_VISUALIZATION_INDICES = [0, 100, 300, 500, 800, 1000]

DEEPLABV3PLUS_RESNET50_OUTPUT_DIR = OUTPUTS_DIR / "deeplabv3plus_resnet50"
DEEPLABV3PLUS_RESNET50_CHECKPOINT_PATH = (
    DEEPLABV3PLUS_RESNET50_OUTPUT_DIR / "deeplabv3plus_resnet50_last.pth"
)
DEEPLABV3PLUS_RESNET50_BEST_CHECKPOINT_PATH = (
    DEEPLABV3PLUS_RESNET50_OUTPUT_DIR / "deeplabv3plus_resnet50_best.pth"
)
DEEPLABV3PLUS_RESNET50_HISTORY_PATH = (
    DEEPLABV3PLUS_RESNET50_OUTPUT_DIR / "history.csv"
)
DEEPLABV3PLUS_RESNET50_STEP_HISTORY_PATH = (
    DEEPLABV3PLUS_RESNET50_OUTPUT_DIR / "step_history.csv"
)
DEEPLABV3PLUS_RESNET50_METRICS_PATH = (
    DEEPLABV3PLUS_RESNET50_OUTPUT_DIR / "metrics.txt"
)
DEEPLABV3PLUS_RESNET50_BEST_METRICS_PATH = (
    DEEPLABV3PLUS_RESNET50_OUTPUT_DIR / "best_metrics.txt"
)
DEEPLABV3PLUS_RESNET50_TRAINING_CURVES_PATH = (
    DEEPLABV3PLUS_RESNET50_OUTPUT_DIR / "training_curves.png"
)
DEEPLABV3PLUS_RESNET50_STEP_LOSS_CURVE_PATH = (
    DEEPLABV3PLUS_RESNET50_OUTPUT_DIR / "step_loss_curve.png"
)
DEEPLABV3PLUS_RESNET50_PREDICTIONS_GRID_PATH = (
    DEEPLABV3PLUS_RESNET50_OUTPUT_DIR / "predictions_grid.png"
)

DEEPLABV3PLUS_RESNET50_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

DEEPLABV3PLUS_RESNET50_NUM_EPOCHS = 30
DEEPLABV3PLUS_RESNET50_LEARNING_RATE = 9.759918974787204e-05
DEEPLABV3PLUS_RESNET50_OPTIMIZER = "adam"
DEEPLABV3PLUS_RESNET50_WEIGHT_DECAY = 0.0
DEEPLABV3PLUS_RESNET50_SCHEDULER = "plateau"
DEEPLABV3PLUS_RESNET50_LOSS = "ce"
DEEPLABV3PLUS_RESNET50_LOG_EVERY_N_BATCHES = 50
DEEPLABV3PLUS_RESNET50_ENCODER_WEIGHTS = "imagenet"
DEEPLABV3PLUS_RESNET50_VISUALIZATION_INDICES = [0, 100, 300, 500, 700]

SEGFORMER_B0_OUTPUT_DIR = OUTPUTS_DIR / "segformer_b0"
SEGFORMER_B0_CHECKPOINT_PATH = SEGFORMER_B0_OUTPUT_DIR / "segformer_b0_last.pth"
SEGFORMER_B0_BEST_CHECKPOINT_PATH = SEGFORMER_B0_OUTPUT_DIR / "segformer_b0_best.pth"
SEGFORMER_B0_HISTORY_PATH = SEGFORMER_B0_OUTPUT_DIR / "history.csv"
SEGFORMER_B0_STEP_HISTORY_PATH = SEGFORMER_B0_OUTPUT_DIR / "step_history.csv"
SEGFORMER_B0_METRICS_PATH = SEGFORMER_B0_OUTPUT_DIR / "metrics.txt"
SEGFORMER_B0_BEST_METRICS_PATH = SEGFORMER_B0_OUTPUT_DIR / "best_metrics.txt"
SEGFORMER_B0_TRAINING_CURVES_PATH = SEGFORMER_B0_OUTPUT_DIR / "training_curves.png"
SEGFORMER_B0_STEP_LOSS_CURVE_PATH = SEGFORMER_B0_OUTPUT_DIR / "step_loss_curve.png"
SEGFORMER_B0_PREDICTIONS_GRID_PATH = SEGFORMER_B0_OUTPUT_DIR / "predictions_grid.png"

SEGFORMER_B0_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

SEGFORMER_B0_NUM_EPOCHS = 30
SEGFORMER_B0_LEARNING_RATE = 1e-4
SEGFORMER_B0_OPTIMIZER = "adam"
SEGFORMER_B0_WEIGHT_DECAY = 0.0
SEGFORMER_B0_SCHEDULER = "none"
SEGFORMER_B0_LOSS = "ce"
SEGFORMER_B0_LOG_EVERY_N_BATCHES = 50
SEGFORMER_B0_ENCODER_WEIGHTS = "imagenet"
SEGFORMER_B0_VISUALIZATION_INDICES = [0, 100, 300, 500, 700]
